[workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[dependencies]
python = "3.12.*"
pillow = "==10.2.0"
cairosvg = ">=2.8.2,<3"

[pypi-dependencies]
esphome = ">=2024.10.3, <2025"

[tasks]
upload = "esphome run self.yaml"
